version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - ./app/:/usr/src/app
    environment:
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBNAME: ${DBNAME}
      DBHOST: ${DBHOST}
      PORT: ${SERVER_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
