version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - ./app/:/usr/src/app
    environment:
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DBNAME: ${DBNAME}
      DBHOST: ${DBHOST}
      SERVER_PORT: 3000
