-- clean the tables
DELETE FROM SENSOR_DATA;
DELETE FROM SENSOR;
DELETE FROM BUILDING;
DELETE FROM TOKEN;

-- delete the tables
DROP TABLE SENSOR_DATA;
DROP TABLE SENSOR;
DROP TABLE BUILDING;
DROP TABLE TOKEN;

CREATE TABLE IF NOT EXISTS BUILDING(
	name VARCHAR(50) PRIMARY KEY,
	address VARCHAR(100),
	numFloors INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SENSOR(
	public_id UUID PRIMARY KEY,
	private_id UUID UNIQUE NOT NULL,
	name VARCHAR(50) NOT NULL,
	floor INTEGER NOT NULL,
	maxpeople INTEGER NOT NULL,
	roomtype VARCHAR (50) NOT NULL,
	building VARCHAR(50) NOT NULL,
	FOREIGN KEY (building) REFERENCES BUILDING(name) ON DELETE CASCADE,
	UNIQUE (building, floor, name)
);

CREATE TABLE IF NOT EXISTS SENSOR_DATA(
	time TIMESTAMP NOT NULL,
	current_people REAL NOT NULL,
	new_people REAL NOT NULL,
	sensor_id UUID NOT NULL,
	PRIMARY KEY (time, sensor_id),
	FOREIGN KEY (sensor_id) REFERENCES SENSOR(public_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TOKEN(
	token VARCHAR(25) PRIMARY KEY,
	validity TIMESTAMP NOT NULL
);

-- insert a pseudo-real token for testing
INSERT INTO TOKEN VALUES ('AAAAABBBBBCCCCCDDDDDEEEEE', to_timestamp(1891961465));

-- select all tokens
SELECT * FROM TOKEN;