version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    network_mode: "host"
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
  
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    network_mode: "host"

  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379
    network_mode: "host"
